project:
  type: website
  output-dir: docs

website:
  title: "Statistica I"
  navbar:
    left:
      - href: index.qmd
        text: Homepage

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: Contenuto della pagina
    highlight-style: ayu

editor: visual