---
title: "Statistica I"
subtitle: "CdL in Scienze Statistiche ed Economiche, Università Milano-Bicocca"
lang: it
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
page-layout: full
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, template.css]
    toc: true
    toc-title: Indice
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
---

L'obiettivo primario del Corso [Statistica I]{.blue} (6 CFU) è fornire agli studenti i principali strumenti della [statistica descrittiva]{.orange} univariata e bivariata.

## Materiale didattico

### Testi di riferimento

- Piccolo, D. (2010), [*Statistica*](https://www.mulino.it/isbn/9788815139023), Terza edizione, Il Mulino.
- Cicchitelli, G., D'Urso P. e Minozzo, M. (2022), [*Statistica. Principi e metodi*](https://he.pearson.it/catalogo/642), Quarta edizione, Pearson.

### Testo di consultazione

- Piccolo, D. (2020). [*Statistica per le decisioni*](https://www.mulino.it/isbn/9788815272201), Terza edizione, Il Mulino.
- Spiegelhalter, D. (2020). [*L'arte della statistica*](https://www.einaudi.it/catalogo-libri/scienze-sociali/sociologia/larte-della-statistica-david-spiegelhalter-9788806246624/). Einaudi.

### Materiale didattico

[Nota]{.orange}: la dicitura §2.1 --- §2.4 indica che vanno considerate le Sezioni §2.1, §2.2, §2.3 e §2.4 del libro di testo (Piccolo, 2010).

| Argomenti                            | Materiale didattico                        | Ulteriore materiale               |
|------------------------|---------------------------|----------------------|
| Introduzione al corso                | [Slides introduzione](slides/sl_intro.pdf) | §1.1 --- §1.8                     |
|                                      | **STATISTICA UNIVARIATA**                  |                                   |
| Sommatorie                           | [Slides unità A.1](slides/sl_A1.pdf)       |                                   |
| *Esercizi*                           | [Esercizi 0](exe/exe_0.html)               |                                   |
| Concetti preliminari                 | [Slides unità A.2](slides/sl_A2.pdf)       | §2.1 --- §2.4, §2.6               |
| Distribuzioni di frequenza           | [Slides unità B](slides/sl_B.pdf)          | §3.1 --- §3.5                     |
| **Esercitazione**                    | [Esercitazione 1](exe/es_1.pdf)          |                                   |
| *Esercizi*                           | [Esercizi 1](exe/exe_1_bis.html)           |  |
| Indici di posizione                  | [Slides unità C](slides/sl_C.pdf)          | §4.1 --- §4.4, §4.6, §4.9         |
| **Applicazioni**                     | [Slides unità D](slides/sl_D.pdf)          |                                   |
|                                      | [Slides unità E](slides/sl_E.pdf)          |                                   |
| **Esercitazione**                    | [Esercitazione 2](exe/es_2.pdf)          |                                   |
| *Esercizi*                           | [Esercizi 2](exe/exe_2_bis.html)           | |
| Indici di variabilità                | [Slides unità F.1](slides/sl_F1.pdf)          | §5.1 --- §5.3                     |
| Mutua variabilità e concentrazione   | [Slides unità F.2](slides/sl_F2.pdf)      | §5.4 --- §5.5                     |
| Istogrammi & boxplot                 | [Slides unità G](slides/sl_G.pdf)          | §3.4, §6.4, §6.5                  |
| Simmetria, curtosi, multimodalità    | [Slides unità H](slides/sl_H.pdf)          | §6.1 --- §6.3                     |
| **Esercitazione**                    | [Esercitazione 3]          |                                   |
| *Esercizi*                           | [Esercizi 3](exe/exe_3_bis.html)           |  |
| Dati qualitativi, eterogeneità       | [Slides unità I](slides/sl_I.pdf)          | §5.7                              |
| **Esercitazione**                    | [Esercitazione 4](exe/es_4.pdf)          |                                   |
| *Esercizi*                           | [Esercizi 4](exe/exe_4_bis.html)           |  |
|                                      | **STATISTICA BIVARIATA**                   |                                   |
| Covarianza e correlazione            | [Slides unità J](slides/sl_J.pdf)          | §7.1, §7.6 --- §7.7               |
| Regressione lineare semplice         | [Slides unità K](slides/sl_K.pdf)          | §22.1 --- §22.4, §22.8            |
| **Applicazione**                     | [Slides unità L](slides/sl_L.pdf)          | §22.9                             |
| Correlazione parziale                | [Slides unità M](slides/sl_M.pdf)          | §7.6                              |
| **Esercitazione**                    | [Esercitazione 5](exe/es_5.pdf)          |                                   |
| *Esercizi*                           | [Esercizi 5](exe/exe_5_bis.html)           | |
| Analisi della varianza               | [Slides unità N](slides/sl_N.pdf)          | §7.4                              |
| **Esercitazione**                    | [Esercitazione 6](exe/es_6.pdf)          |                                   |
| *Esercizi*                           | [Esercizi 6](exe/exe_6_bis.html)           |  |
| Tabelle di contingenza               | [Slides unità O](slides/sl_O.pdf)          | §7.1 --- §7.5                     |
| La dipendenza tra variabili          | [Slides unità P](slides/sl_P.pdf)          | §7.4                              |
| **Esercitazione**                    | [Esercitazione 7](exe/exe_7.html)          |                                   |
| *Esercizi*                           | [Esercizi 7](exe/exe_7_bis.html)           | [Soluzione 7](exe/sol_exe_7.html) |
| **Simulazione d'esame**              | [Esercitazione 8](exe/exe_8.html)          |                                   |
| La pandemia di COVID-19 in Lombardia | [Slides unità Q](slides/sl_Q.pdf)          |                                   |
|                                      | **ESAMI PASSATI**                          |                                   |
|                                      | [Esami passati](exe/exe_8_bis.html)        |                                   |

### Approfondimenti

<!-- #### Quotidiani -->

<!-- -   [La vera America è qui da noi: italiani più ricchi](https://www.corriere.it/esteri/20_giugno_25/vera-america-qui-noi-italiani-piu-ricchi-d4cc4256-b64b-11ea-9dea-5ac3c9ec7c08.shtml). *Corriere della Sera* del 25 Giugno 2020. -->

<!-- -   [A caccia di un milione di scienziati dei dati. Inizia la democratizzazione della data science](https://nova.ilsole24ore.com/nova24-tech/a-caccia-di-un-milione-di-scienziati-dei-dati-inizia-la-democratizzazione-della-data-science/). *Nóva, de Il Sole 24 ore* del 20 Marzo 2019. -->

#### Articoli scientifici (in inglese)

-   [Azzalini, A. (1990)](approfondimenti/Azzalini1990.pdf). A look at some data on the Old Faithful geyser. *Journal of the Royal Statistical Society. Series C (Applied Statistics)* **39**(3), 357--365.

-   [Hyndman, R. J. and Yanan, F. (1996)](approfondimenti/Hyndman1996.pdf). Sample quantiles in statistical packages. *The American Statistician* **50**(4), 361--365.

-   [Muliere, P. and Parmigiani, G. (1993)](approfondimenti/Muliere1993.pdf). Utility and means in the 1930s. *Statistical Science* **8**(4), 421--432.

-   [Schwertman, N. C., Gilks, A. J., and Cameron, J. (1990)](approfondimenti/Schwertman1990.pdf). A simple noncalculus proof that the median minimizes the sum of the absolute deviations. *The American Statistician* **44**(1), 38--38.

-   [Spiegelhalter, D. (2004)](approfondimenti/Spiegelhalter2004.pdf). Shipman's statistical legacy. *Significance*.

-   [Wainer, H. (1984)](approfondimenti/Wainer1984.pdf). How to display data badly. *The American Statistician* **38**(2), 137--147.

### Altro

-   [Cronistoria della statistica](approfondimenti/cronistoria.pdf)

## Modalità d'esame

La modalità di verifica delle conoscenze acquisite durante il corso è basata su una [prova scritta]{.orange}. La prova d'esame comprende [domande aperte]{.blue} di carattere teorico ed [esercizi]{.blue} simili a quelli visti a lezione. 

<!-- Inoltre, gli studenti che otterranno una [valutazione alla prova scritta maggiore o uguale a 26]{.blue} dovranno obbligatoriamente sostenere una [prova orale aggiuntiva]{.orange}. -->

## Propedeuticità

Il Corso non prevede propedeuticità. È caldamente consigliata, tuttavia, la conoscenza di nozioni di matematica di base previste dai programmi delle scuole secondarie superiori.

## Ricevimento

Per fissare un appuntamento, si prega di contattare il docente in anticipo via posta elettronica all'indirizzo `tommaso.rigon@unimib.it`. Il ricevimento è fissato ogni [martedì alle ore 17.30]{.blue}.

------------------------------------------------------------------------

#### Ringraziamenti

Si ringrazia Matteo Borrotti, Guido Masarotto e Bruno Scarpa per aver reso disponibile gran parte del materiale su cui questo corso è basato.
