<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tommaso Rigon">

<title>Statistica I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="19_11_2024_files/libs/clipboard/clipboard.min.js"></script>
<script src="19_11_2024_files/libs/quarto-html/quarto.js"></script>
<script src="19_11_2024_files/libs/quarto-html/popper.min.js"></script>
<script src="19_11_2024_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="19_11_2024_files/libs/quarto-html/anchor.min.js"></script>
<link href="19_11_2024_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="19_11_2024_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="19_11_2024_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="19_11_2024_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="19_11_2024_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice</h2>
   
  <ul>
  <li><a href="#problema-1" id="toc-problema-1" class="nav-link active" data-scroll-target="#problema-1">Problema 1</a></li>
  <li><a href="#problema-2" id="toc-problema-2" class="nav-link" data-scroll-target="#problema-2">Problema 2</a></li>
  <li><a href="#problema-3" id="toc-problema-3" class="nav-link" data-scroll-target="#problema-3">Problema 3</a></li>
  </ul>
</nav>
</div>
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistica I</h1>
<p class="subtitle lead">Esame 19 Novembre 2024</p>
</div>


<div class="quarto-title-meta-author column-page-left">
  <div class="quarto-title-meta-heading">Autore/Autrice</div>
  <div class="quarto-title-meta-heading">Affiliazione</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Tommaso Rigon </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            DEMS
          </p>
      </div>
  </div>

<div class="quarto-title-meta column-page-left">

      
  
    
  </div>
  


</header>


<section id="problema-1" class="level2">
<h2 class="anchored" data-anchor-id="problema-1">Problema 1</h2>
<p>Nell’A.A. 2024/25, durante il corso Statistica I, è stato condotto un esperimento. Agli studenti presenti è stato chiesto <span class="blue">per due volte</span> di indovinare il numero di biglie presenti in una bottiglia, la quale conteneva <span class="math inline">282</span> biglie. Al <code>primo tentativo</code> (<span class="math inline">x</span>) non è stata fornita alcuna informazione di supporto, mentre al <code>secondo tentativo</code> (<span class="math inline">y</span>) sono state fornite delle informazioni aggiuntive, come la dimensione delle biglie e la capacità della bottiglia.</p>
<p>Dopo alcune analisi preliminari, sono state ritenute <em>valide</em> un totale di <span class="math inline">n = 79</span> risposte. Tali risposte sono state rappresentate nel seguente diagramma a dispersione.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="700"></p>
</figure>
</div>
</div>
</div>
<p>Vengono inoltre riportate nel seguito alcune quantità di potenziale interesse:</p>
<p><span class="math display">
\sum_{i=1}^{79} x_i = 19451, \quad  \sum_{i=1}^{79} x_i^2 = 5255977, \quad \sum_{i=1}^{79} y_i = 21256, \quad \sum_{i=1}^{79} y_i^2 = 6054602,
</span> <span class="math display">
\sum_{i=1}^{79} x_i y_i = 5293892, \quad  \frac{1}{79}\sum_{i=1}^{79} y_i^3 = 23072804.33, \quad \frac{1}{79}\sum_{i=1}^{79} y_i^4 = 7360399442.
</span></p>
<ol type="1">
<li><p>Si calcolino le varianze delle variabili <code>primo tentativo</code> e <code>secondo tentativo</code> e la loro correlazione.</p></li>
<li><p>Si consideri il seguente modello di regressione lineare: <span class="math display">
y_i = \alpha + \beta x_i + \epsilon_i, \qquad i=1,\dots,79.
</span> Si ottengano delle stime per <span class="math inline">\alpha</span> e <span class="math inline">\beta</span> nel modo che si ritiene più opportuno.</p></li>
<li><p>Si fornisca quindi un’<span class="orange">interpretazione</span> per i coefficienti stimati al punto precedente. In che modo gli studenti hanno cambiato la loro opinione, se lo hanno fatto?</p></li>
<li><p>Si calcoli la varianza residuale del modello stimato. Inoltre, sapendo che <span class="math inline">x_9 = 187</span> e <span class="math inline">y_9 = 466</span>, a quanto ammonta il residuo corrispondente <span class="math inline">r_9</span>?</p></li>
<li><p>Si ottenga l’indice di bontà di adattamento <span class="math inline">R^2</span> e lo si <span class="orange">interpreti</span> nel contesto del problema.</p></li>
<li><p>Si calcoli l’indice di curtosi di Pearson <span class="math inline">\kappa</span> per la variabile <code>secondo tentativo</code> e se ne dia un’interpretazione. Suggerimento: si ricordi che <span class="math inline">(a - b)^4 = a^4 - 4a^3b + 6 a^2 b^2 - 4 a b^3 + b^4</span>.</p></li>
</ol>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Schema della soluzione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Questo primo punto è stato svolto correttamente da quasi la totalità degli iscritti alla prova. Alcuni studenti <span class="orange">non</span> hanno però calcolato la correlazione. A partire dai valori riportati nel testo dell’esame, a meno di piccole discrepanze dovute all’approssimazione usata, si otteneva infatti che:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Statistica</th>
<th style="text-align: right;">Valore</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Media x (primo tentativo)</td>
<td style="text-align: right;">246.215190</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media y (secondo tentativo)</td>
<td style="text-align: right;">269.063291</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Varianza x (primo tentativo)</td>
<td style="text-align: right;">5909.434706</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varianza y (secondo tentativo)</td>
<td style="text-align: right;">4245.477007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Covarianza(x, y)</td>
<td style="text-align: right;">763.821823</td>
</tr>
<tr class="even">
<td style="text-align: left;">Correlazione(x,y)</td>
<td style="text-align: right;">0.152495</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol start="2" type="1">
<li><p>Era possibile stimare <span class="math inline">\alpha</span> e <span class="math inline">\beta</span> tramite <span class="blue">minimi quadrati</span>, usando le formule consuete, ottenendo: <span class="math display">
\hat{\beta}= 0.129255, \quad  \hat{\alpha} = 237.238837.
</span> Anche questa domanda è stata svolta correttamente dalla larga maggioranza degli studenti. Vi sono stati alcuni (pochi) <span class="orange">errori grossolani</span>, come ad es. l’uso di formule sbagliate, errori di conto banali, etc.</p></li>
<li><p>L’interpretazione dei coefficienti stimati ha causato molte difficoltà. Nella maggior parte degli esami è stato osservato che al secondo tentativo le stime risultavano più accurate rispetto al primo, ovvero più vicine a 282, come emerge dalle medie. Inoltre, è stato talvolta notato che la varianza del secondo tentativo è inferiore a quella del primo. Sebbene queste affermazioni siano corrette, esse non rispondono alla domanda posta, che riguardava specificamente l’interpretazione dei coefficienti e del modello stimato. Ecco, ad esempio, quanto si poteva commentare:</p>
<ol type="a">
<li>Anzitutto, si poteva notare che <span class="math inline">\hat{\alpha}</span> rappresenta la stima, al secondo tentativo, di un ipotetico studente che al primo tentativo avesse dichiarato “0”. Sebbene si tratti di un caso poco realistico, <span class="math inline">\hat{\alpha}</span> ha proprio questo significato. Inoltre, <span class="math inline">\hat{\beta} = 0.129</span> implica che, in media, al crescere del valore del primo tentativo, aumenta anche il valore stimato del secondo. Più precisamente, ogni biglia aggiuntiva nel primo tentativo corrisponde, in media, a un incremento di <span class="math inline">0.129</span> biglie nel secondo tentativo.</li>
<li>Ciò che in pochi hanno commentato è il fatto che <span class="math inline">\hat{\beta} &lt; 1</span>, analogamente a quanto avviene nei dati di Galton relativi alle altezze di padri e figli. Combinando questo aspetto con la stima di <span class="math inline">\hat{\alpha}</span>, si deduce che coloro che avevano <span class="orange">sottostimato</span> il numero di biglie al primo tentativo (ad esempio, <span class="math inline">x_1 = 100</span>) hanno in media <span class="blue">aumentato</span> la loro stima al secondo tentativo (<span class="math inline">\hat{y}_1 = 250.16</span>). Viceversa, coloro che avevano <span class="orange">sovrastimato</span> il numero di biglie al primo tentativo (ad esempio, <span class="math inline">x_2 = 400</span>) hanno in media <span class="blue">diminuito</span> la loro stima al secondo tentativo (<span class="math inline">\hat{y}_2 = 288.9407</span>).</li>
<li>Complessivamente, gli studenti <span class="blue">hanno cambiato opinione</span>. Si osservi che una perfetta coerenza con la propria opinione precedente si sarebbe ottenuta nel caso in cui <span class="math inline">\hat{\alpha} = 0</span>, <span class="math inline">\hat{\beta} = 1</span> e, soprattutto, <span class="math inline">R^2 = 1</span>, cioè con dati perfettamente allineati alla bisettrice. Tuttavia, si riscontra che <span class="math inline">R^2 \approx 0.02</span>, oltre a valori differenti per <span class="math inline">\hat{\alpha}</span> e <span class="math inline">\hat{\beta}</span>. Pertanto, la tendenza media a correggere quanto fatto al primo tentativo (cioè quanto descritto al punto b.) spiega solo una piccola frazione della variabilità di <span class="math inline">y</span>. Gli studenti hanno effettivamente cambiato opinione, ma lo hanno fatto senza considerare in modo significativo quanto stimato nel primo tentativo.</li>
</ol></li>
<li><p>Usando le formule illustrate a lezione, la <span class="orange">varianza residuale</span> si calcola essere pari a <span class="math inline">\text{var}(r) = 4146.749496</span>. Inoltre, si ottiene che il valore previsto è <span class="math inline">\hat{y}_9 = 261.409453</span> e pertanto il <span class="orange">residuo</span> corrispondente è <span class="math inline">r_9 = y_9 - \hat{y}_9 = 204.590547</span>.</p></li>
<li><p>Si ottiene che l’indice di bontà d’adattamento è pari a <span class="math inline">R^2 = \rho^2 = 0.023255</span>. Come detto in precedenza, questo significa la tendenza media a correggere quanto fatto al primo tentativo spiega solo una piccola frazione della variabilità di <span class="math inline">y</span>. Gli studenti hanno effettivamente cambiato opinione, ma lo hanno fatto senza considerare in modo significativo quanto stimato nel primo tentativo.</p></li>
<li><p>Questo esercizio coinvolgeva numeri molto grandi e, di conseguenza, moltissimi hanno commesso errori di calcolo. L’indice di curtosi di Pearson si otteneva a partire dai dati a disposizione attraverso la seguente scomposizione: <span class="math display">
\kappa_y = \frac{1}{\sigma_y^4}\frac{1}{n}\sum_{i=1}^n(y_i - \bar{y})^4 = \frac{1}{\sigma_y^4}\left[\frac{1}{n}\sum_{i=1}^ny_i^4 - 4 \bar{y}\frac{1}{n} \sum_{i=1}^ny_i^3 + 6 \bar{y}^2\frac{1}{n}\sum_{i=1}^ny_i^2 - 4 \bar{y}^3 \frac{1}{n} \sum_{i=1}^n y_i + \bar{y}^4\right].
</span> Da questa scrittura, facendo attenzione a non dimenticare alcun termine, si otteneva che <span class="math inline">\kappa_y = 5.29635</span>, che implica un <span class="orange">eccesso di curtosi</span> (code pesanti) essendo che <span class="math inline">\kappa_y &gt; 3</span>.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="problema-2" class="level2">
<h2 class="anchored" data-anchor-id="problema-2">Problema 2</h2>
<p>Durante l’A.A. 2024/25 agli studenti del corso di Statistica I è stato chiesto di identificare la tipologia di <span class="math inline">5</span> diversi indici. I risultati di questo esperimento didattico sono riportati nella tabella seguente, che mostra le frequenze congiunte delle variabili <code>domanda</code> e <code>risposta</code> (variabile binaria: <span class="math inline">0</span> risposta errata, <span class="math inline">1</span> risposta corretta). La numerosità campionaria <span class="math inline">n = 310</span> rappresenta il numero complessivo di risposte fornite.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Domanda</th>
<th style="text-align: right;">Risposta errata (<span class="math inline">0</span>)</th>
<th style="text-align: right;">Risposta corretta (<span class="math inline">1</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a. (indice pari a <span class="math inline">0</span>)</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">b. (varianza)</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c.&nbsp;(differenza semplice media)</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">d.&nbsp;(media geometrica)</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e. (scarto interquartile)</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
<ol type="1">
<li><p>Si ottengano le frequenze relative della variabile <code>risposta</code> <span class="orange">condizionatamente</span> a ciascun valore della variabile <code>domanda</code>.</p></li>
<li><p>Si stabilisca quale tra le distribuzioni della variabile <code>risposta</code>, condizionatamente a ciascun valore della variabile <code>domanda</code>, risulta maggiormente <span class="blue">eterogenea</span>.</p></li>
<li><p>(<span class="blue">Teoria</span>) Sia <span class="math inline">y</span> una variabile <span class="orange">binaria</span>, ovvero i cui valori <span class="math inline">y_1,\dots,y_n</span> sono pari <span class="math inline">0</span> oppure a <span class="math inline">1</span>. Il valore <span class="math inline">0</span> ha frequenze relativa pari <span class="math inline">f_0</span> mentre il valore <span class="math inline">1</span> ha frequenze relativa <span class="math inline">f_1</span>. Si mostri che in tal caso l’indice di eterogeneità Gini è pari a <span class="math inline">2</span> volte la varianza, ovvero: <span class="math display">
G = 2\: \text{var}(y).
</span></p></li>
<li><p>Si stabilisca, tramite opportuni indici, se la variabile <code>risposta</code> è dipendente <span class="orange">in distribuzione</span> dalla variabile <code>domanda</code>. Si fornisca un’interpretazione di questi risultati.</p></li>
<li><p>Si stabilisca, tramite opportuni indici, se la variabile <code>risposta</code> è dipendente <span class="orange">in media</span> dalla variabile <code>domanda</code>. Si fornisca un’interpretazione di questi risultati.</p></li>
</ol>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Schema della soluzione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Questa prima domanda ha, con mia sorpresa, causato qualche difficoltà. Erano richieste le frequenze relative <span class="orange">condizionate</span>, le quali sono pari a</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Risposta errata</th>
<th style="text-align: right;">Risposta corretta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">0.800</td>
<td style="text-align: right;">0.200</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">0.333</td>
<td style="text-align: right;">0.667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">0.717</td>
<td style="text-align: right;">0.283</td>
</tr>
<tr class="even">
<td style="text-align: left;">d</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">0.924</td>
<td style="text-align: right;">0.076</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Si noti che ciascuna riga somma ad 1, pertanto questa tabella colleziona in forma compatta <span class="math inline">5</span> distribuzioni di frequenza.</p>
<ol start="2" type="1">
<li>Una variabile qualitativa è tanto più eterogenea quanto più le sue frequenze relative risultano simili tra loro. Era richiesto identificare la più eterogenea tra le 5 distribuzioni calcolate al punto 1. Come hanno fatto molti, si potevano calcolare gli indici di eterogeneità di Gini (o di Shannon) per ciascuna variabile, ottenendo:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Risposta errata</th>
<th style="text-align: right;">Risposta corretta</th>
<th style="text-align: right;">Gini</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">0.800</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: right;">0.320</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">0.333</td>
<td style="text-align: right;">0.667</td>
<td style="text-align: right;">0.444</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">0.717</td>
<td style="text-align: right;">0.283</td>
<td style="text-align: right;">0.406</td>
</tr>
<tr class="even">
<td style="text-align: left;">d</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.738</td>
<td style="text-align: right;">0.387</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">0.924</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">0.140</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Da ciò si evince che la <span class="blue">risposta b</span> era la <span class="orange">più eterogenea</span>, avendo il valore di Gini maggiore. In questo caso molto semplice, è stata accettata come corretta anche la risposta di chi si è limitato a confrontare le frequenze relative, notando che la distanza tra <span class="math inline">0.333</span> e <span class="math inline">0.667</span> era la più piccola. Tuttavia, non è stata considerata corretta la risposta di chi ha scritto semplicemente “b” senza fornire alcuna giustificazione.</p>
<ol start="3" type="1">
<li><p>Questa domanda era leggermente più complessa delle altre e serviva per accedere alle valutazioni più alte. Come mostrato anche durante le esercitazioni, la varianza di una variabile binaria è data da: <span class="math display">
\text{var}(y) = f_1(1 - f_1) = f_0(1 - f_0),
</span> ricordando che <span class="math inline">f_1 = 1 - f_0</span>. Di conseguenza: <span class="math display">
2\text{var}(x) = f_1(1 - f_1) + f_0(1 - f_0) = f_0(1 - f_0) + f_1(1 - f_1) = \sum_{j=0}^1 f_j(1 - f_j) = G.
</span> Questa era una semplice dimostrazione. Sono state accettate anche dimostrazioni alternative, ovviamente purché corrette.</p></li>
<li><p>Questa era una domanda “standard”, affrontata varie volte a lezione. Per verificare l’indipendenza in distribuzione, era possibile utilizzare l’indice di connessione <span class="math inline">\chi^2</span>. A tal fine, si potevano anzitutto calcolare le <span class="orange">frequenze attese</span>, che sono date da:</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Risposta errata</th>
<th style="text-align: right;">Risposta corretta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">36.581</td>
<td style="text-align: right;">23.419</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">38.410</td>
<td style="text-align: right;">24.590</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">36.581</td>
<td style="text-align: right;">23.419</td>
</tr>
<tr class="even">
<td style="text-align: left;">d</td>
<td style="text-align: right;">37.190</td>
<td style="text-align: right;">23.810</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">40.239</td>
<td style="text-align: right;">25.761</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Dalla tabella, si concludeva, dopo qualche calcolo, che <span class="math inline">\chi^2 = 90.612537</span> e inoltre che <span class="math inline">\chi^2_\text{norm} = 0.292299</span>. Di conseguenza, si osserva una discreta dipendenza in distribuzione. Questo implica semplicemente che la frazione di risposte corrette dipende dalla domanda, suggerendo che probabilmente le domande presentavano livelli di difficoltà diversi tra loro.</p>
<ol start="5" type="1">
<li>Questa domanda è stata inaspettatamente molto problematica: alcuni studenti hanno calcolato le <span class="orange">medie delle frequenze assolute</span>, che ovviamente non ha alcun senso. Veniva richiesto di valure la dipendenza <span class="orange">in media</span> della variabile <code>risposta</code> in funzione della variabile <code>domanda</code>. Si noti che la variabile risposta è <span class="blue">numerica</span> e assume i valori <span class="math inline">0</span> ed <span class="math inline">1</span>. Di conseguenza, le frequenze relative condizionate della risposta corretta corrispondono alle medie del gruppo, mentre le varianze condizionate sono pari alla metà dei coefficienti di Gini precedentemente calcolati. In primo luogo, andava pertanto ottenuta la seguente tabella:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 53%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Risposta corretta (Media del gruppo)</th>
<th style="text-align: right;">Gini</th>
<th style="text-align: right;">Varianza</th>
<th style="text-align: right;"><span class="math inline">n_j</span></th>
<th style="text-align: right;"><span class="math inline">d_j^2</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">9.600</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">0.667</td>
<td style="text-align: right;">0.444</td>
<td style="text-align: right;">0.222</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">14.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">0.283</td>
<td style="text-align: right;">0.406</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">12.183</td>
</tr>
<tr class="even">
<td style="text-align: left;">d</td>
<td style="text-align: right;">0.738</td>
<td style="text-align: right;">0.387</td>
<td style="text-align: right;">0.193</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">11.803</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">4.621</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Si noti inoltre che <span class="math inline">\bar{x} = 0.390323</span>. A partire da questa tabella, si otteneva che: <span class="math inline">\mathscr{D}^2_\text{tr} = \sum_{j=1}^k n_j(\bar{x}_j - \bar{x})^2 = 21.563144,</span> e che <span class="math inline">\mathscr{D}^2_\text{en} = \sum_{j=1}^k d^2_j = 52.207824.</span> Da ciò si conclude che <span class="math inline">\mathscr{D} = \mathscr{D}^2_\text{tr} + \mathscr{D}^2_\text{en} = 73.770968</span>. Un indice di dipendenza in media è quindi dato da: <span class="math display">
\eta^2 = \frac{\mathscr{D}^2_\text{tr}}{\mathscr{D}} = 0.292299.
</span> Da questo si deduce una discreta dipendenza in media. <span class="orange">Nota</span>: questo valore è identico a <span class="math inline">\chi^2_\text{norm}</span>, nonostante sia stato ottenuto attraverso una procedura completamente diversa. Non si tratta di una coincidenza, anche se la dimostrazione di questo fatto non è immediata. In presenza di variabili binarie, infatti, vale che <span class="math inline">\eta^2 = \chi^2_\text{norm}</span> (!).</p>
</div>
</div>
</div>
</section>
<section id="problema-3" class="level2">
<h2 class="anchored" data-anchor-id="problema-3">Problema 3</h2>
<p>Siano <span class="math inline">x_1,\dots,x_n</span> ed <span class="math inline">y_1,\dots,y_n</span> due insiemi di dati e siano <span class="math inline">w_1,\dots,w_n</span> dei dati trasformati tali che <span class="math inline">w_i = x_i + y_i</span>, per <span class="math inline">i=1,\dots,n</span>.</p>
<ol type="1">
<li><p>In quali circostanze la relazione <span class="math inline">\text{var}(w) = \text{var}(x) + \text{var}(y)</span> risulta verificata?</p></li>
<li><p>Si <span class="blue">dimostri</span> la seguente disuguaglianza: <span class="math inline">|\text{cov}(x, y)| \le \text{sqm}(x)\text{sqm}(y).</span></p></li>
</ol>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Schema della soluzione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Si tratta di argomenti trattati a lezione, per cui si rimanda alle slides e/o al libro di testo. Per quel che riguarda il primo punto, la relazione è verificata se <span class="math inline">\text{cov}(x, y) = 0</span>.</p>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiato!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiato!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="19_11_2024_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>