<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tommaso Rigon">

<title>Statistica I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="21_11_2022_files/libs/clipboard/clipboard.min.js"></script>
<script src="21_11_2022_files/libs/quarto-html/quarto.js"></script>
<script src="21_11_2022_files/libs/quarto-html/popper.min.js"></script>
<script src="21_11_2022_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="21_11_2022_files/libs/quarto-html/anchor.min.js"></script>
<link href="21_11_2022_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="21_11_2022_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="21_11_2022_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="21_11_2022_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="21_11_2022_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice</h2>
   
  <ul>
  <li><a href="#problema-1" id="toc-problema-1" class="nav-link active" data-scroll-target="#problema-1">Problema 1</a></li>
  <li><a href="#problema-2" id="toc-problema-2" class="nav-link" data-scroll-target="#problema-2">Problema 2</a></li>
  <li><a href="#problema-3" id="toc-problema-3" class="nav-link" data-scroll-target="#problema-3">Problema 3</a></li>
  </ul>
</nav>
</div>
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistica I</h1>
<p class="subtitle lead">Esame 21 Novembre 2022</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Tommaso Rigon </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            DEMS
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<section id="problema-1" class="level2">
<h2 class="anchored" data-anchor-id="problema-1">Problema 1</h2>
<p>Numerose teorie sulla causa della schizofrenia coinvolgono cambiamenti nell’attività di una sostanza chiamata <em>dopamina</em> nel sistema nervoso centrale. In questo studio, <span class="math inline">n = 25</span> pazienti schizofrenici sono stati trattati con farmaci antipsicotici e, dopo un certo periodo di tempo, sono stati classificati come psicotici o non-psicotici dal personale ospedaliero. Da ogni paziente sono stati prelevati campioni di liquido cerebrospinale di cui è stata misurata la dopamina b-idrossilata (un enzima). I dati sono riportati di seguito, misurati in nmol(ml)(h)/(mg) di proteina.</p>
<p>I medici sono interessati a capire se e quanto la dopamina differisce nei due gruppi di pazienti.</p>
<p><strong>Pazienti giudicati psicotici (A)</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.0150 0.0204 0.0208 0.0222 0.0226 0.0245 0.0270 0.0275 0.0306 0.0320</code></pre>
</div>
</div>
<p><strong>Pazienti giudicati non-psicotici (B)</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.0104 0.0105 0.0112 0.0116 0.0130 0.0145 0.0154 0.0156 0.0170 0.0180
[11] 0.0200 0.0200 0.0210 0.0230 0.0252</code></pre>
</div>
</div>
<ol type="1">
<li><p>Si fornisca la definizione formale di funzione di ripartizione empirica e di quantile-<span class="math inline">p</span>. Inoltre, si chiarisca qual è la relazione intercorrente tra questi concetti.</p></li>
<li><p>Si considerino i dati dei pazienti giudicati psicotici e le seguenti classi non equispaziate: <span class="math inline">(0.01, 0.02]</span>, <span class="math inline">(0.02, 0.0225]</span>, <span class="math inline">(0.0225, 0.025]</span>, <span class="math inline">(0.025, 0.0275]</span>, <span class="math inline">(0.0275, 0.0325]</span>. Per queste classi, si calcolino frequenze assolute, frequenze relative e densità. Quindi, si disegni l’istogramma associato.</p></li>
<li><p>Sarebbe corretto disegnare un istogramma relativo ai pazienti giudicati psicotici utilizzando <span class="math inline">15</span> classi equispaziate? Perchè?</p></li>
<li><p>Per entrambi i gruppi di pazienti, si identifichino media, mediana, primo e terzo quartile. Si confrontino quindi i boxplot corrispondenti (includendo eventuali valori anomali) e si <strong>commentino i risultati</strong>.</p></li>
<li><p>Senza fare riferimento ai dati sopra elencati, si <strong>dimostri</strong> che la media dei valori di dopamina per tutti gli <span class="math inline">n = 25</span> pazienti <span class="math inline">\bar{x}</span> coincide con una media pesata delle medie aritmetiche di ciascun gruppo <span class="math inline">\bar{x}_A</span> (pazienti psicotici) e <span class="math inline">\bar{x}_B</span> (pazienti non-psicotici). Quindi, la si calcoli con i dati a disposizione.</p></li>
<li><p>Si proponga un indice adeguato per misurare se e quanto il livello di dopamina differisce tra i due gruppi di pazienti. Quindi, si <strong>commentino i risultati</strong>.</p></li>
</ol>
<section id="schema-della-soluzione" class="level4">
<h4 class="anchored" data-anchor-id="schema-della-soluzione">Schema della soluzione</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Frequenze assolute</th>
<th style="text-align: right;">Frequenze relative</th>
<th style="text-align: right;">Densità</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(0.01,0.02]</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.02,0.0225]</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">1200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.0225,0.025]</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">800</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.025,0.0275]</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.0275,0.0325]</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">400</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Istogramma dei dati dei pazienti giudicati psicotici (A)</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="21_11_2022_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="1750"></p>
</div>
</div>
<p>Statistiche descrittive</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Media gruppo (A)  Media gruppo (B) Mediana gruppo (A) Mediana gruppo (B)
[1,]           0.02426    0.01642666667            0.02355             0.0156</code></pre>
</div>
</div>
<p>Primo e terzo quartile dei pazienti giudicati psicotici (A)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   25%    75% 
0.0208 0.0275 </code></pre>
</div>
</div>
<p>Primo e terzo quartile dei pazienti giudicati non-psicotici (B)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   25%    75% 
0.0116 0.0200 </code></pre>
</div>
</div>
<p>Confronto tra i due boxplot:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="21_11_2022_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="1750"></p>
</div>
</div>
<p>Devianza entro i gruppi:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0005464733333</code></pre>
</div>
</div>
<p>Devianza tra i gruppi:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003681666667</code></pre>
</div>
</div>
<p>Devianza totale</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00091464</code></pre>
</div>
</div>
<p>Indice <span class="math inline">\eta^2</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4025263127</code></pre>
</div>
</div>
</section>
</section>
<section id="problema-2" class="level2">
<h2 class="anchored" data-anchor-id="problema-2">Problema 2</h2>
<p>È stato condotto un esperimento per studiare l’effetto della <code>caffeina</code> sulle prestazioni in un semplice compito fisico. A trenta studenti universitari maschi è stato chiesto di picchiettare le dita sul tavolo. Sono stati poi divisi a caso in tre gruppi di 10, i quali hanno ricevuto dosi diverse di caffeina (0 ml, 100 ml e 200 ml). Due ore dopo il trattamento, ogni individuo è stato invitato a picchiettare le dita sul tavolo. Viene quindi registrato il <code>numero di battiti</code> al minuto.</p>
<p>I dati sono elencati nel seguito. La caffeina influisce sulle prestazioni in questo compito?</p>
<p><code>numero di battiti</code>, 0 ml di <code>caffeina</code> (<span class="math inline">j=1</span>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 242 245 244 248 247 248 242 244 246 242</code></pre>
</div>
</div>
<p><code>numero di battiti</code>, 100 ml di <code>caffeina</code> (<span class="math inline">j=2</span>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 248 246 245 247 248 250 247 246 243 244</code></pre>
</div>
</div>
<p><code>numero di battiti</code>, 200 ml di <code>caffeina</code> (<span class="math inline">j=3</span>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 246 248 250 252 248 250 246 248 245 250</code></pre>
</div>
</div>
<p>Siano <span class="math inline">y_{ij}</span> ed <span class="math inline">x_{ij}</span> i dati relativi al <code>numero di battiti</code> e i ml di <code>caffeina</code>, rispettivamente, per <span class="math inline">i = 1,\dots,10</span> e per le tre dosi di caffeina <span class="math inline">j=1,2,3</span>. Pertanto, utilizzando questa notazione, i dati sopra elencati corrispondono ad esempio ai simboli <span class="math inline">y_{11} = 242</span> e <span class="math inline">y_{21} = 245</span>; <span class="math inline">x_{11} = \dots = x_{10,1} = 0</span>; <span class="math inline">x_{13} = \dots = x_{10,3} = 200</span>.</p>
<p>Vengono inoltre riportate nel seguito alcune quantità di potenziale interesse:</p>
<p><span class="math display">
\frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10} y_{ij} = 246.5, \quad  \frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10} y_{ij}^2 = 60768.7666666667, \quad \frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10} x_{ij} y_{ij} = 24766.6666666667,
</span></p>
<p><span class="math display">
\frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10} x_{ij} = 100, \quad \frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10} x_{ij}^2 = 16666.6666666667.
</span></p>
<ol type="1">
<li><p>Si disegni il diagramma a dispersione che mette in relazione la variabile <code>caffeina</code> (<span class="math inline">x</span>) con la variabile <code>numero di battiti</code> (<span class="math inline">y</span>).</p></li>
<li><p>Si calcolino le varianze delle variabili <code>caffeina</code> e <code>numero di battiti</code> e la loro correlazione.</p></li>
<li><p>Si consideri il seguente modello di regressione lineare: <span class="math display">
y_{ij} = \alpha + \beta x_{ij} + \epsilon_{ij}, \qquad i=1,\dots,10, \quad j=1,\dots,3.
</span> Si ottengano delle stime per <span class="math inline">\alpha</span> e <span class="math inline">\beta</span> nel modo che si ritiene più opportuno.</p></li>
<li><p>Si disegni quindi la retta di regressione ottenuta al punto precedente nel grafico ottenuto al punto (a). Si fornisca quindi un’<strong>interpretazione</strong> per i coefficienti stimati. In particolare, la caffeina influisce sul comportamento di queste persone?</p></li>
<li><p>In base al modello stimato, se venisse somministrata una dose di <span class="math inline">50</span>ml di <code>caffeina</code> ad un individuo, qual è il <code>numero di battiti</code> previsto?</p></li>
<li><p>Si ottenga l’indice di bontà di adattamento <span class="math inline">R^2</span> e lo si interpreti nel contesto del problema.</p></li>
</ol>
<section id="schema-della-soluzione-1" class="level4">
<h4 class="anchored" data-anchor-id="schema-della-soluzione-1">Schema della soluzione</h4>
<p>Grafico a dispersione, con retta di regressione stimata</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="21_11_2022_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="1750"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Media x Media y  Varianza x  Varianza y Covarianza xy Correlazione xy
[1,]     100   246.5 6666.666667 6.516666667   116.6666667    0.5597313934</code></pre>
</div>
</div>
<p>Coefficienti del modello di regressione stimati <span class="math inline">(\hat{\alpha},\hat{\beta})</span>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
   244.7500      0.0175 </code></pre>
</div>
</div>
<p>Previsione del numero di battiti quando <span class="math inline">x = 50</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 245.625</code></pre>
</div>
</div>
<p>Indice <span class="math inline">R^2</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3132992327</code></pre>
</div>
</div>
</section>
</section>
<section id="problema-3" class="level2">
<h2 class="anchored" data-anchor-id="problema-3">Problema 3</h2>
<p>Si considerino le variabili <code>caffeina</code> e <code>numero di battiti</code> presentate nell’esercizio precedente, aventi media <span class="math inline">\bar{x}</span> e <span class="math inline">\bar{y}</span>, rispettivamente.</p>
<ol type="1">
<li><p>Si <strong>dimostri</strong> che <span class="math display">
\frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10}(y_{ij} - \bar{y})^2 \ge \frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10}(y_{ij} - \hat{\alpha} - \hat{\beta} x_{ij})^2,
</span> dove <span class="math inline">\hat{\alpha}</span> e <span class="math inline">\hat{\beta}</span> sono le stime ai minimi quadrati.</p></li>
<li><p>È inoltre possibile dimostrare che <span class="math display">
\frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10}(y_{ij} - \hat{\alpha} - \hat{\beta} x_{ij})^2 \ge \frac{1}{30}\sum_{j=1}^3\sum_{i=1}^{10}(y_{ij} - \bar{y}_j)^2,
</span> dove <span class="math inline">\bar{y}_j</span> per <span class="math inline">j=1, 2 ,3</span>, rappresentano la medie aritmetiche del <code>numero di battiti</code> per ciascun dosaggio di caffeina. Si fornisca un’<strong>interpretazione</strong> per questa disuguaglianza e la si usi per <strong>dimostrare</strong> che vale la seguente relazione <span class="math display">
\eta^2 \ge R^2,
</span> dove <span class="math inline">\eta^2</span> rappresenta il rapporto di correlazione.</p></li>
<li><p>(Per la lode). Si dimostri la disuguaglianza precedente.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="21_11_2022_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>