---
title: "Analisi dei voti"
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
dataset <- read_delim("data_voti.csv", delim = ";")

# Rimuovo valori mancanti
dataset <- na.omit(dataset)

table(dataset$AA, dataset$Esito)

aggregate(Esito ~ AA,length, data = filter(dataset, Appello == "I"))

aggregate(Esito ~ AA, function(x) sum(x == "RIT"), data = filter(dataset, Appello == "I"))
aggregate(Esito ~ AA, function(x) sum(x == "ASS"), data = filter(dataset, Appello == "I"))
aggregate(Esito ~ AA, function(x) sum(x == "RIFIUTATO"), data = filter(dataset, Appello == "I"))
aggregate(Esito ~ AA, function(x) sum(x == "INS" | x == "RIT"), data = filter(dataset, Appello == "I"))

# Rimuovo assenti
dataset <- dataset %>% filter(Esito != "ASS") %>% filter(Esito != "RIT")
aggregate(Esito ~ AA, function(x) mean(x == "INS"), data = filter(dataset, Appello == "I"))
aggregate(Esito ~ AA, function(x) sum(x == "INS"), data = filter(dataset, Appello == "I"))

dataset <- dataset %>% filter(Esito != "RIFIUTATO")
```

```{r}
dataset <- filter(dataset,  Esito != "INS")
dataset <- dataset %>% mutate(Esito = as.numeric(Esito))

ggplot(data  = filter(dataset, Appello == "I"), aes(x = AA, y = Esito, fill = AA)) + geom_boxplot() + theme_bw() + xlab("Anno Accademico") + theme(legend.position = "none") + scale_y_continuous(breaks = 18:31)
```

```{r}
ggplot(data  = filter(dataset, Appello %in% c("I", "II", "III")), aes(x = AA, y = Esito, fill = Appello)) + geom_boxplot() + theme_light() + xlab("Anno Accademico") + theme(legend.position = "top") + scale_y_continuous(breaks = 18:31)
```

```{r}
aggregate(Esito ~ AA, mean, data = filter(dataset, Appello == "I"))
```

```{r}
aggregate(Esito ~ AA, median, data = filter(dataset, Appello == "I"))
```

```{r}
summary(lm(Esito ~ AA, data = filter(dataset, Appello == "I")))
```

```{r}
summary(lm(Esito ~ Appello  + AA, data = dataset))
```

