<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.163">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistica I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistica I</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Home</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenuto della pagina</h2>
   
  <ul>
  <li><a href="#soluzione-di-alcuni-esercizi" id="toc-soluzione-di-alcuni-esercizi" class="nav-link active" data-scroll-target="#soluzione-di-alcuni-esercizi">Soluzione di <strong>alcuni</strong> esercizi</a>
  <ul class="collapse">
  <li><a href="#esercizio-a" id="toc-esercizio-a" class="nav-link" data-scroll-target="#esercizio-a">Esercizio A</a></li>
  <li><a href="#esercizio-c" id="toc-esercizio-c" class="nav-link" data-scroll-target="#esercizio-c">Esercizio C</a></li>
  <li><a href="#esercizio-d" id="toc-esercizio-d" class="nav-link" data-scroll-target="#esercizio-d">Esercizio D</a></li>
  <li><a href="#esercizio-e" id="toc-esercizio-e" class="nav-link" data-scroll-target="#esercizio-e">Esercizio E</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistica I</h1>
<p class="subtitle lead">Esercizi 2: indici di posizione</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="soluzione-di-alcuni-esercizi" class="level2">
<h2 class="anchored" data-anchor-id="soluzione-di-alcuni-esercizi">Soluzione di <strong>alcuni</strong> esercizi</h2>
<p>Le seguenti soluzioni sono state gentilmente fornite dal <strong>tutor di Statistica I</strong> dell’A.A. 2021/2022, <em>Alex Alborghetti</em>, che ringrazio. Le soluzioni sono state quindi riviste dal docente, che si assume le responsabilità di eventuali sviste ed errori.</p>
<section id="esercizio-a" class="level3">
<h3 class="anchored" data-anchor-id="esercizio-a">Esercizio A</h3>
<p>È dato il vettore di osservazioni:</p>
<p><span class="math display">\[
x = (-4,5,3,1,-1,3,-1,1,0,3,2)
\]</span></p>
<p>Ricordando la definizione di media aritmetica:</p>
<p><span class="math display">\[
\bar{x} = \frac{1}{n}\sum_{i=1}^nx_i = \frac{-4+5+3+\cdots + 2}{11} = 1.091
\]</span></p>
<p>Inoltre, la definizione di mediana è:</p>
<p><span class="math display">\[
\text{Me}(x) = \begin{cases}
          x_{(\frac{n+1}{2})} &amp;\qquad  n \text{ dispari}\\
         \big{[}x_{(n/2)} + x_{(n/2 +1)}\big{]}/2 &amp; \qquad n \text{ pari}\\
\end{cases}
\]</span></p>
<p>dove <span class="math inline">\(x_{(i)}\)</span> indica l’i-esimo valore in ordine crescente di <span class="math inline">\(x\)</span>. Si trova facilmente che <span class="math inline">\(\text{Me}(x) = x_{(6)} = 1\)</span>.</p>
<p>Sia <span class="math inline">\(f(x)\)</span> una trasformazione monotona dei dati di partenza, allora <span class="math inline">\(\text{Me}(f(x)) = f(\text{Me}(x))\)</span>.</p>
<p>La media, invece, gode della proprietà di linearità, tale per cui <span class="math inline">\(\bar{y} = a + b\bar{x}\)</span>. Grazie a queste due proprietà, si possono ricavare le seguenti:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(y\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\text{Me}(y)\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bar{y}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(e^x\)</span></td>
<td style="text-align: center;"><span class="math inline">\(e^{\text{Me}(x)} = e\)</span></td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x+4\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\text{Me}(x) + 4 = 5\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{x}+4 = 5.091\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(-3x+1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-3 \text{Me}(x) +1=-2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-3\bar{x}+1 = -2.273\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(x^2\)</span></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
<p>I tre spazi vuoti della tabella, invece, vanno necessariamente completati trasformando manualmente i dati e calcolando gli indici richiesti.</p>
<p>Si trova che <span class="math inline">\(\bar{y} = n^{-1}\sum_{i=1}^n e^{x_i} = 20.295\)</span>, <span class="math inline">\(\text{Me}(x^2) = 4\)</span> e <span class="math inline">\(\bar{y} = n^{-1}\sum_{i=1}^n x_i^2 = 6.909\)</span>. I risultati sono stati arrotondati a tre cifre decimali.</p>
</section>
<section id="esercizio-c" class="level3">
<h3 class="anchored" data-anchor-id="esercizio-c">Esercizio C</h3>
<p>La distanza di un negozio dal magazzino può essere espressa come lo scarto <span class="math inline">\(|x_i - a|\)</span>km, dove <span class="math inline">\(x_i\)</span> è il kilometro al quale si trova il negozio e <span class="math inline">\(a\)</span> è il chilometro al quale si trova il magazzino.</p>
<p>Si deve cercare quel valore <span class="math inline">\(a\)</span> tale per cui il doppio (andata e ritorno) della somma di questi scarti viene minimizzata. Il valore <span class="math inline">\(a\)</span> deve, pertanto, corrispondere alla mediana, che vale <span class="math inline">\(134\)</span>.</p>
<p>La distanza totale percorsa per rifornire tutti e cinque i negozi è pari a <span class="math inline">\(1178\)</span>km. Se avessimo posizionato il magazzino sul chilometro pari alla media, che vale <span class="math inline">\(200.2\)</span>km, avremmo dovuto percorrere <span class="math inline">\(1319.2\)</span>km.</p>
</section>
<section id="esercizio-d" class="level3">
<h3 class="anchored" data-anchor-id="esercizio-d">Esercizio D</h3>
<p>Una comune approssimazione della media quando i dati sono suddivisi in classi è data da: <span class="math display">\[
\bar{x} \approx \frac{1}{n} \sum_{j=1}^k n_jm_j,
\]</span> dove <span class="math inline">\(m_j\)</span> è il punto centrale del j-esimo intervallo ed <span class="math inline">\(n_j\)</span> è la sua frequenza assoluta. Abbiamo già visto negli <a href="sol_exe_1.html">esercizi 1</a> come ricavare le frequenze assolute:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Classe</th>
<th style="text-align: center;">Freq. cumulata</th>
<th style="text-align: center;">Freq. Assoluta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(249, 250]</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">(250, 251]</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(251, 252]</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">42 - 15 = 27</td>
</tr>
<tr class="even">
<td style="text-align: left;">(252, 253]</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">60 - 42 = 18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(253, 254]</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">70 - 60 = 10</td>
</tr>
<tr class="even">
<td style="text-align: left;">(254, 255]</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71 - 70 = 1</td>
</tr>
</tbody>
</table>
<p>Quindi, possiamo calcolare la media come:</p>
<p><span class="math display">\[
\bar{x} \approx \frac{0\cdot125+15\cdot250.5+27\cdot251.5+18\cdot252.5+10\cdot253.5+1\cdot254.5}{71} = 251.866.
\]</span></p>
<p>Invece, una comune approssimazione della mediana quando i dati sono suddivisi in classi è data da: <span class="math display">\[
\text{Me}(x) \approx a_{j-1} + (a_j - a_{j-1})\frac{1/2 - F(a_{j-1})}{F(a_{j})-F(a_{j-1})},
\]</span></p>
<p>dove <span class="math inline">\((a_{j-1}, a_{j}]\)</span> è la classe alla quale la mediana appartiene ed <span class="math inline">\(F(\cdot)\)</span> è la funzione di ripartizione empirica. Nel nostro caso, è evidente che la mediana, ovvero l’osservazione <span class="math inline">\(x_{(36)}\)</span>, appartiene all’intervallo <span class="math inline">\((251,252]\)</span>. Sappiamo, inoltre, che <span class="math inline">\(F(252) = 42/71 = 0.592\)</span> e <span class="math inline">\(F(251) = 15/71 = 0.211\)</span>. Sostituendo tutti i valori nella formula, si ricava: <span class="math display">\[
\text{Me}(x) \approx 251.759.
\]</span></p>
<p>Tutti i risultati sono arrotondati a tre cifre decimali.</p>
<p>Una comune approssimazione del primo quartile quando i dati sono suddivisi in classi è, invece, data da: <span class="math display">\[
Q_{0.25} \approx a_{j-1} + (a_j - a_{j-1})\frac{0.25 - F(a_{j-1})}{F(a_{j})-F(a_{j-1})},
\]</span></p>
<p>dove <span class="math inline">\((a_{j-1}, a_{j}]\)</span> è la classe alla quale il primo quartile appartiene ed <span class="math inline">\(F(\cdot)\)</span> è la funzione di ripartizione empirica. Poiché il primo quartile sta nell’intervallo <span class="math inline">\((251,252]\)</span>, dato che <span class="math inline">\(F(252) = 0.592\)</span> e <span class="math inline">\(F(251) = 0.211\)</span>, sostituendo nella formula troviamo che <span class="math inline">\(Q_{0.25} \approx 251.102\)</span>.</p>
<p>Una comune approssimazione del terzo quartile quando i dati sono suddivisi in classi è data da: <span class="math display">\[
Q_{0.75} \approx a_{j-1} + (a_j - a_{j-1})\frac{0.75 - F(a_{j-1})}{F(a_{j})-F(a_{j-1})},
\]</span></p>
<p>dove <span class="math inline">\((a_{j-1}, a_{j}]\)</span> è la classe alla quale il primo quartile appartiene ed <span class="math inline">\(F(\cdot)\)</span> è la funzione di ripartizione empirica. Poiché il terzo quartile sta nell’intervallo <span class="math inline">\((252,253]\)</span> dato che <span class="math inline">\(F(252) = 0.592\)</span> e <span class="math inline">\(F(253) = 60/71 = 0.845\)</span>, sostituendo nella formula troviamo che <span class="math inline">\(Q_{0.75} \approx 252.625\)</span>.</p>
</section>
<section id="esercizio-e" class="level3">
<h3 class="anchored" data-anchor-id="esercizio-e">Esercizio E</h3>
<p>La mediana della variabile <span class="math inline">\(x\)</span> vale approssimativamente <span class="math inline">\(17\)</span>. Il primo quartile vale approssimativamente <span class="math inline">\(16\)</span>, il terzo <span class="math inline">\(22\)</span>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>