---
title: 'Statistica I'
subtitle: 'Esercizi 6: analisi della varianza'
lang: it
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
page-layout: full
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, ../template.css]
    toc: true
    toc-title: Indice
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
---

# [Homepage](../index.html)

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = F, eval = T, message = F, warning = F, error = F, comment = NA, cache = F, include = T, R.options = list(width = 100), collapse = T, dpi = 200, fig.align = "center", fig.height = 4, fig.width = 8)
```

Alcune delle seguenti soluzioni sono state gentilmente fornite dal [tutor di Statistica I]{.blue} dell'A.A. 2021/2022, [Alex Alborghetti]{.orange}, che ringrazio. Le soluzioni sono state quindi riviste dal docente, che si assume le responsabilità di eventuali sviste ed errori. 


## Esercizio A

Un certo gruppo di polli e stato suddiviso casualmente in tre gruppi. Successivamente i tre gruppi sono stati alimentati con tre diete differenti, chiamate A, B, C. Siamo interessati alla variabile $x_j$, per $j=1,\dots,3$, ovvero gli incrementi di peso dopo 6 settimane in ciascuna dieta. Alcuni dati di sintesi sono riportati nella seguente tabella:

| Dieta | Numero di polli | $\bar{x}_j$ | $\sigma^2_j$ |
| ------|-----------------|-------------|--------------|
| A | 14 | 218.8 | 2728.6 |
| B | 9  | 246.4 | 2930.0 |
| C | 10 | 328.9 | 2385.1 |

I pesi sono stati rilevati in grammi. 

1. Quanto vale la varianza totale?

1. Quantificare la "correlazione" la variabili `dieta` ed `incremento del peso`.

:::{.callout-note collapse=true}
#### Schema della soluzione

È noto, dalla scomposizione della devianza totale, che vale la seguente relazione:

$$
\mathcal{D}^2 = \underbrace{\sum_{j = 1}^k \sum_{i = 1}^{n_j}(x_{ij}-\bar{x}_j)^2}_{\mathcal{D}^2_\text{en}} + \underbrace{\sum_{j=1}^kn_j(\bar{x}_j-\bar{x})^2}_{\mathcal{D}^2_\text{tr}},
$$

Evidentemente, dividendo per $n$ entrambi i membri, la scomposizione risulta valida anche per le varianze. Calcoliamo quindi le due varianze e sommiamole. Abbiamo già a disposizione le varianze di ciascun gruppo, dunque si può dimostrare che:

$$
\sigma^2_{\text{en}} = \frac{1}{n} \sum_{j=1}^k n_j\sigma_j^2 = 2679.4.
$$

Per quanto riguarda la varianza tra i gruppi, calcoliamo anzitutto la media, si dimostri che vale la seguente relazione:

$$
\bar{x} = \frac{1}{n} \sum_{j=1}^k n_j\bar{x}_j= 259.7.
$$

Allora, la varianza tra i gruppi vale:

$$
 \sigma^2_{\text{tr}} = \frac{1}{n} \sum_{j=1}^kn_j(\bar{x}_j-\bar{x})^2 = 2209.0.
$$

Pertanto, la varianza totale sarà pari a $\sigma^2 = 2679.4 + 2209.0 = 4888.4$. I risultati sono arrotondati al primo decimale.

Per calcolare la "correlazione" tra dieta e incremento del peso utilizziamo l'indice $\eta^2$, definito come:

$$
\eta^2 = 1 - \frac{\text{devianza  entro  i  gruppi}}{\text{devianza totale}}.
$$

Si può dimostrare (lo si faccia per esercizio) che tale indice è equivalente al complemento ad uno del rapporto tra varianza entro i gruppi e varianza totale. Allora, con i nostri dati:

$$
\eta^2 = 1 - 2679.4/(2679.4+2209.0) = 0.45.
$$

C'è quindi una moderata "correlazione" tra le due variabili. Il risultato è stato arrotondato a due decimali.
:::

## Esercizio B

Durante una sperimentazione clinica, un gruppo di pazienti è stato suddiviso in tre sotto-gruppi: il primo, di $5$ pazienti, comprendente i pazienti con età tra i $20$ e i $40$ anni; il secondo, di 5, tra i $40$ e $60$ ed il terzo, di tre pazienti, con $60$ o più anni.

Per tutti i pazienti è stato rilevato il tempo di reazione all'inoculazione di un farmaco. I risultati, in minuti, sono rappresentati dai seguenti valori (nell'ordine per i gruppi A, B, C): `76, 52, 178, 113, 83, 80, 124, 46, 88, 36, 94, 51, 74`.

------------------------

1. Si valutino il tempo medio e la varianza dei tempi di reazione per i tre gruppi.

1. Si valuti la frazione di varianza spiegata dai gruppi. 

:::{.callout-note collapse=true}
#### Schema della soluzione

Le medie e le varianze dei tempi di reazione di ciascun gruppo sono state calcolate e vengono riassunte nella tabella seguente:

| Gruppo | $\bar{x}_j$ | $\sigma^2_j$ |
|:-------|:-----------:|:------------:|
| 20-40  |    100.4    |    1884.2    |
| 40-60  |    74.8     |    991.4     |
| 60+    |     73      |    308.7     |

(i risultati sono arrotondati al primo decimale).

La varianza tra i gruppi è interpretabile come la varianza spiegata dalle medie. La media totale è pari a $\bar{x} = 84.2$, allora:

$$
\sigma^2_\text{tr} = \frac{1}{n} \sum_{j=1}^kn_j(\bar{x}_j-\bar{x})^2 = 163.9.
$$

Considerato che a varianza totale è pari a $\sigma^2 = (1/n) \sum_{i=1}^n(x_i-\bar{x})^2 = 1341.102$, la proporzione di varianza spiegata è circa del $12.2\%$.
:::

## Esercizio C

I dati riportati nella tabella che segue fanno riferimento a un esperimento in cui a 15 cavie è stata somministrata una stessa quantità di un veleno. Le cavie sono state poi suddivise casualmente in 3 gruppi (di numerosità diverse) e ciascun gruppo è stato sottoposto a un trattamento. 

Alle cavie del primo gruppo è stato somministrato l’antidoto A, a quelle del secondo l’antidoto B e a quelle del terzo l’antidoto C. Per ciascuna cavia si è quindi misurato, in decine di ore, il tempo di sopravvivenza.

| Trattamento (Antidoto) | 1 | 2| 3 | 4 | 5| 6| 7| 8 | 
|------------------------|-|-|-|-|-|-|-|-|
| A | 0.22 | 0.14 | 0.44 | 0.59 |
| B | 2.80 | 3.60 | 2.80 | | | 
| C | 1.70 | 2.00 | 1.52 | 2.60 | 1.67 | 1.90 | 0.82 | 1.90 |

Scopo dell’esperimento è stabilire se i tre antidoti hanno la stessa efficacia. Si quantifichi quindi la dipendenza in media dei tempi di sopravvivenza dal tipo di antidoto.

:::{.callout-note collapse=true}
#### Schema della soluzione

Per comodità, vengono calcolate e riassunte nella seguente tabella alcune quantità utili:

| Gruppo | $\bar{x}_j$ | $\sigma^2_j$ |
|:-------|:-----------:|:------------:|
| A      |    0.35     |     0.03     |
| B      |    3.07     |     0.14     |
| C      |    1.76     |     0.22     |

I risultati sono stati arrotondati a due decimali. La dipendenza in media si misura tramite l'indice $\eta$, cioè il complemento ad uno del rapporto tra la varianza entro i gruppi e la varianza totale. La varianza entro i gruppi può essere calcolata come segue:

$$
\sigma^2_\text{en} = \frac{1}{n} \sum_{j=1}^k n_j\sigma_j^2 = 0.15.
$$

Per il calcolo della varianza totale, utilizziamo la definizione: $\sigma^2 = (1/n) \sum_{i=1}^n(x_i-\bar{x})^2 = 1.01$, con $\bar{x} = 1.65$. I risultati sono arrotondati a due decimali. In conclusione, possiamo dire che i tre antidoti non sembrano avere la stessa efficacia, dato che:

$$
\eta^2 = 1 - 0.15/1.01 = 0.85.
$$
:::

