---
title: 'Statistica I'
subtitle: 'Esercitazione 3: variabilità, istogrammi, boxplot, simmetria, curtosi'
lang: it
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
page-layout: full
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, ../template.css]
    toc: true
    toc-title: Indice
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
---

# [Homepage](../index.html)

Alcuni dei problemi di questa esercitazione [non]{.orange} sono stati svolti a lezione. Si consiglia agli studenti di provare a risolvere i problemi autonomamente. 


```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = F, eval = T, message = F, warning = F, error = F, comment = NA, cache = F, include = T, R.options = list(width = 100), collapse = T, dpi = 200, fig.align = "center", fig.height = 4, fig.width = 8)
```


## Strani indici

Si dica se gli indici elencati di seguito possono o non possono essere interpretati come una misura di posizione oppure di variabilità di un certo insieme di dati tutti positivi, $y_1, \dots, y_n$. Il simbolo $\mathcal{Q}_p$ indica il quantile $p$.

1. 
$$
\frac{1}{n^2}\sum_{i=1}^n\sum_{j=1}^n(y_i - y_j).
$$

1. 
$$
\frac{1}{n^2}\sum_{i=1}^n\sum_{j=1}^n(y_i - y_j)^2.
$$

1. 
$$
\frac{1}{2n^2}\sum_{i=1}^n\sum_{j=1}^n|y_i - y_j|.
$$

1. 
$$
\exp\left\{\frac{1}{n}\sum_{i=1}^n\log{x_i}\right\}.
$$

1. 
$$
\mathcal{Q}_{0.5} - \mathcal{Q}_{0.25} + |\mathcal{Q}_{0.5} - \mathcal{Q}_{0.75}|
$$

::: {.callout-note collapse=true}

## Schema della soluzione

1. Questo indice è sempre pari a zero, quindi certamente non è adatto per misurare nè la posizione nè la variabilità.

1. Questo indice è pari al doppio della varianza campionaria.

1. Questo indice è una misura robusta di variabilità.

1. Questo indice è una riscrittura della media geometrica $\mathbb{G}$.

1. Questo indice è una riscrittura dello scarto interquartile. Si noti infatti che $|\mathcal{Q}_{0.5} - \mathcal{Q}_{0.75}| = \mathcal{Q}_{0.75} - \mathcal{Q}_{0.5}$.

:::

<!-- ## Tubi catodici -->

<!-- Una vecchia fabbrica di televisori produce due tipi di tubi catodici: il tipo A e il tipo B. I tubi catodici hanno tempi di durata media, rispettivamente di $1495$ ore e $1875$ ore e scarti quadratici medi rispettivamente di $280$ ore e $310$ ore. In generale, è preferibile il tubo catodico che ha la durata più alta e variabilità più bassa.  -->

<!-- Quale dei due tubi catodici è preferibile? -->

<!-- ::: {.callout-note collapse=true} -->

<!-- ## Schema della soluzione -->

<!-- I tubi catodici di tipo B hanno durata media maggiore dei tubi catodici di tipo A. Anche la varianza dei tubi catodici di tipo B è maggiore di quelli di tipo A. -->

<!-- Tuttavia i due scarti quadratici medi non sono immediatamente confrontabili, poichè le medie delle due tipologie sono diverse. Un indicatore più adeguato in questo caso è il coefficiente di variazione: -->

<!-- $$ -->
<!-- \text{CV}_A = \frac{\sigma_A}{\bar{x}_A} = \frac{280}{1495} \approx 0.187, \quad \text{CV}_B = \frac{\sigma_B}{\bar{x}_B} = \frac{310}{1875} \approx 0.165,  -->
<!-- $$ -->

<!-- Concludiamo quindi che la tipologia B è preferibile, essendo caratterizzata da una media maggiore e un coefficiente di variazione minore.  -->
<!-- ::: -->

## Lampadine

Un'azienda produttrice di lampadine controlla la durata dei suoi prodotti facendo funzionare $n = 200$ lampadine ininterrottamente fino a che si rompono. A determinati istanti di tempo si effettua un controllo e si verifica quante in totale non sono più funzionanti. I dati sono riportati nella tabella seguente

| Tempo | 10 | 30 | 100 | 150 | 200 | 400 | 
|-------|----|----|-----|-----|-----|-----|
| Rotture cumulate | 2 | 20 | 40 | 80 | 120  |170  |

Si noti che $30$ lampadine non si sono mai rotte.

1. Si valuti la "durata media" e si dia un indice di posizione appropriato per sintetizzare la distribuzione delle durate.

2. Si calcoli un opportuno indice di variabilità.

::: {.callout-note collapse=true}

## Schema della soluzione

In primo luogo, ri-organizziamo la tabella in maniera tale da evidenziare gli intervalli considerati

| Tempo | $(0, 10]$ | $(10, 30]$ | $(30, 100]$ | $(100,150]$ | $(150,200]$ | $(200,400]$ | $(400, \infty]$ |
|-------|----|----|-----|-----|-----|-----|--|
| $n_j$ | 2 | 18 | 20 | 40 | 40  | 50  | 30 |
| $f_j$ | 0.01 | 0.09 | 0.10 | 0.20 | 0.20 | 0.25 | 0.15 |
| $F_j$ | 0.01 | 0.1 | 0.20 | 0.40 | 0.60 | 0.85 | 1 |


Si noti che un totale di $200 - 170 = 30$ lampadine non si sono mai rotte entro il tempo $400$. Questo pone delle difficoltà nel calcolo della media. Infatti, non è chiaro quale valore sia il valore centrale dell'intervallo $(400, \infty]$. Qualunque scelta dovrebbe ben essere giustificata.

La mediana non risente di questo problema. La mediana appartiene necessariamente all'intervallo $(150,200]$. Utilizzando l'approssimazione lineare, otteniamo che

$$
\text{Me} \approx 150 + (200 - 150)\frac{0.5 - 0.4}{0.6 - 0.4} = 175.
$$
Per le stesse ragioni menzionate prima, ci sono delle difficoltà nel calcolo della varianza. Consideriamo quindi lo scarto interquartile. Utilizzando l'approssimazione lineare, si ottiene

$$
\mathcal{Q}_{0.25} \approx 100 + (150 - 100)\frac{0.25 - 0.2}{0.4 - 0.2} = 112.5.
$$
$$
\mathcal{Q}_{0.75} \approx 200 + (400 - 200)\frac{0.75 - 0.6}{0.85 - 0.6} = 320.
$$
Pertanto lo scarto interquartile è pari a

$$\mathcal{Q}_{0.75} - \mathcal{Q}_{0.25} = 207.5.$$
:::



