---
title: 'Statistica I'
subtitle: 'Esercizi 2: indici di posizione'
lang: it
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
page-layout: full
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, ../template.css]
    toc: true
    toc-title: Indice
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
---


# [Homepage](../index.html)



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
```

## Soluzione di [alcuni]{.orange} esercizi

Le seguenti soluzioni sono state gentilmente fornite dal [tutor di Statistica I]{.blue} dell'A.A. 2021/2022, [Alex Alborghetti]{.orange}, che ringrazio. Le soluzioni sono state quindi riviste dal docente, che si assume le responsabilità di eventuali sviste ed errori.

### Esercizio A

È dato il vettore di osservazioni:

$$
x = (-4,5,3,1,-1,3,-1,1,0,3,2)
$$ Ricordando la definizione di media aritmetica, si ottiene quindi che: $$
\bar{x} = \frac{1}{n}\sum_{i=1}^nx_i = \frac{-4+5+3+\cdots + 2}{11} = 1.091
$$

Si trova facilmente dalla definizione che $\text{Me}(x) = x_{(6)} = 1$. Sia $f(x)$ una trasformazione monotona dei dati di partenza, allora $\text{Me}(f(x)) = f(\text{Me}(x))$.

La media, invece, gode della proprietà di linearità, tale per cui $\bar{y} = a + b\bar{x}$. Grazie a queste due proprietà, si possono ricavare i seguenti valori:

| $y$     |        $\text{Me}(y)$        |       $\bar{y}$        |
|:--------|:----------------------------:|:----------------------:|
| $e^x$   | $e^{\text{Me}(x)} = e^1 = e$ |           \-           |
| $x+4$   |    $\text{Me}(x) + 4 = 5$    |  $\bar{x}+4 = 5.091$   |
| $-3x+1$ |   $-3 \text{Me}(x) +1=-2$    | $-3\bar{x}+1 = -2.273$ |
| $x^2$   |              \-              |           \-           |

I tre spazi vuoti della tabella, invece, vanno necessariamente completati trasformando [manualmente]{.orange} i dati e calcolando gli indici richiesti.

Si trova che $\bar{y} = n^{-1}\sum_{i=1}^n e^{x_i} = 20.295$, $\text{Me}(x^2) = 4$ e $\bar{y} = n^{-1}\sum_{i=1}^n x_i^2 = 6.909$. I risultati sono stati arrotondati a tre cifre decimali.

### Esercizio C

La distanza di un negozio dal magazzino può essere espressa come lo scarto $|x_i - a|$km, dove $x_i$ è il chilometro al quale si trova il [negozio]{.blue}, mentre $a$ è il chilometro al quale si trova il [magazzino]{.orange}.

Si deve individuare quel valore $a$ tale per cui il doppio (andata e ritorno) della somma di questi scarti viene minimizzata. Il valore $a$ deve, pertanto, corrispondere alla mediana, che vale $134$.

La distanza totale percorsa per rifornire tutti e cinque i negozi è pari a $1178$km. Se avessimo posizionato il magazzino sul chilometro pari alla media, che vale $200.2$km, avremmo dovuto percorrere $1319.2$km.

### Esercizio D

Una tipica approssimazione della media, quando i dati sono suddivisi in classi, è la seguente: $$
\bar{x} \approx \frac{1}{n} \sum_{j=1}^k n_jm_j,
$$ dove $m_j$ è il punto centrale del j-esimo intervallo ed $n_j$ è la sua frequenza assoluta. 

| Classe      | Freq. cumulata | Freq. Assoluta |
|:------------|:--------------:|:--------------:|
| (249, 250\] |       0        |       0        |
| (250, 251\] |       15       |       15       |
| (251, 252\] |       42       |  42 - 15 = 27  |
| (252, 253\] |       60       |  60 - 42 = 18  |
| (253, 254\] |       70       |  70 - 60 = 10  |
| (254, 255\] |       71       |  71 - 70 = 1   |

Quindi, possiamo calcolare la media come:

$$
\bar{x} \approx \frac{0\cdot249.5+15\cdot250.5+27\cdot251.5+18\cdot252.5+10\cdot253.5+1\cdot254.5}{71} = 251.866.
$$

Invece, una comune approssimazione della mediana quando i dati sono suddivisi in classi è data da: $$
\text{Me}(x) \approx a_{j-1} + (a_j - a_{j-1})\frac{1/2 - F(a_{j-1})}{F(a_{j})-F(a_{j-1})},
$$

dove $(a_{j-1}, a_{j}]$ è la classe alla quale la mediana appartiene ed $F(\cdot)$ è la funzione di ripartizione empirica.

Nel nostro caso, la mediana, ovvero l'osservazione $x_{(36)}$, appartiene all'intervallo $(251,252]$. Sappiamo, inoltre, che $F(252) = 42/71 = 0.592$ e $F(251) = 15/71 = 0.211$. Sostituendo tutti i valori nella formula, si ricava: $$
\text{Me}(x) \approx 251.759.
$$ 

Un'approssimazione del primo quartile, quando i dati sono suddivisi in classi, è invece: 
$$
 Q_{0.25} \approx a_{j-1} + (a_j - a_{j-1})\frac{0.25 - F(a_{j-1})}{F(a_{j})-F(a_{j-1})},
$$
dove $(a_{j-1}, a_{j}]$ è la classe alla quale il primo quartile appartiene. Poiché il primo quartile apartiene all'intervallo $(251,252]$, dato che $F(252) = 0.592$ e $F(251) = 0.211$, sostituendo questi valori nella formula troviamo che $Q_{0.25} \approx 251.102$.

L'approssimazione del terzo quartile quando i dati sono suddivisi si ottiene invece tramite la formula: $$
Q_{0.75} \approx a_{j-1} + (a_j - a_{j-1})\frac{0.75 - F(a_{j-1})}{F(a_{j})-F(a_{j-1})},
$$
dove $(a_{j-1}, a_{j}]$ è la classe alla quale il terzo quartile appartiene. 

Poiché il terzo quartile appartiene alla classe $(252,253]$ dato che $F(252) = 0.592$ e $F(253) = 60/71 = 0.845$, sostituendo nella formula troviamo che $Q_{0.75} \approx 252.625$.

### Esercizio H

La mediana della variabile $x$ vale circa $17$. Il primo quartile vale circa $16$, il terzo $22$.
